worker_app: synapse.app.generic_worker
worker_name: worker4

worker_listeners:
 - type: http
   port: 8086
   x_forwarded: true
   resources:
     - names: [client, federation]
 - type: metrics
   port: 9194
   bind_addresses: ['0.0.0.0']

worker_pid_file: /config/worker4.pid
